<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

<!--
EL4126 Robotika (K01) 2023
Nama : Bostang Palaguna
NIM : 13220055
Robot : PUMA 500 robot (model)
-->

<!-- Deskripsi Properti robot -->
<xacro:property name="base_plate_link_mass" value="12" />
<xacro:property name="base_plate_link_height" value="0.05" />  <!-- tinggi-->
<xacro:property name="base_plate_link_width" value="1.5" /> <!-- panjang -->
<xacro:property name="base_plate_link_depth" value="1.5" /> <!-- lebar -->
<xacro:property name="base_mass" value="5" />
<xacro:property name="base_length" value="1" />
<xacro:property name="base_radius" value="0.3" />
<xacro:property name="base_joint_offset_x" value="1.0" />
<xacro:property name="base_joint_offset_y" value="1.0" />
<xacro:property name="waist_length" value="1" />
<xacro:property name="waist_radius" value="0.2" />
<xacro:property name="waist_mass" value="3" />
<xacro:property name="shoulder_length" value="0.5" />
<xacro:property name="shoulder_radius" value="0.2" />
<xacro:property name="shoulder_mass" value="3" />
<xacro:property name="arm_radius" value="0.1" />
<xacro:property name="arm_length" value="0.3" />
<xacro:property name="arm_radius" value="0.1" />

    <!-- include semua konten pada example_include.xacro -->
    <xacro:include filename="example_include.xacro" />

    <!-- This first link called "world" is empty -->
    <link name="world"></link>

    <!-- A simple fixed joint dari empty world link ke base -->
    <!-- The base origin sengaja diberi offset dari  world origin. -->
    <joint name="base_plate_joint" type="fixed">
        <origin xyz="${base_joint_offset_x} ${base_joint_offset_y} 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="base_plate_link"/>        
    </joint>

        <!-- base_plate_link berupa pelat tipis persegi panjang lebar.-->

        <!-- Catatan: -->
        <!-- - visual origin Z diatur half the box height, so that the link origin sits at the bottom of the box -->
        <!-- - collision diatur identik dengan visual -->
        <!-- - inertial parameters diatur secara manual -->  
    <link name="base_plate_link">
    
        <!-- Visual property base link -->
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="${base_plate_link_width} ${base_plate_link_depth} ${base_plate_link_height}" />
            </geometry>
            <material name="green">
                <color rgba="0.2 1 0.2 1"/>
            </material>
        </visual>
        <!-- Collision property base link -->
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <box size="${base_plate_link_width} ${base_plate_link_depth} ${base_plate_link_height}" />
            </geometry>
        </collision>
        <!-- Momen inersia base link -->
        <xacro:inertial_box mass="${base_plate_link_mass}" x="${base_plate_link_width}" y="${base_plate_link_depth}" z="${base_plate_link_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="base_joint" type="revolute"> 
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_plate_link"/>
        <child link="base_link"/>
        <axis xyz="0 0 1"/> 
        <limit lower="0" upper="${2*pi}" velocity="100" effort="100"/> 
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_length/2+base_plate_link_height}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${base_length}" radius="${base_radius}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0 0 ${base_length/2+base_plate_link_height}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${base_length}" radius="${base_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${base_mass}" length="${base_length}" radius="${base_radius}">
            <origin xyz="0 0 ${base_length/2+base_plate_link_height}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="waist_joint" type="revolute">
        <origin xyz="0 0 ${base_length+base_plate_link_height}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="waist_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="0" upper="${3*pi/2}" velocity="100" effort="100"/> 
    </joint>

    <link name="waist_link">
        <visual>
            <origin xyz="${waist_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>                
                <cylinder length="${waist_length}" radius="${waist_radius}" />
            </geometry>
            <material name="yellow" />
        </visual>
        <collision>
            <origin xyz="${waist_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="${waist_length}" radius="${waist_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${waist_mass}" length="${waist_length}" radius="${waist_radius}">
            <origin xyz="${waist_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="shoulder_joint" type="revolute">
        <!-- <origin xyz="${waist_length} 0 ${base_length/2}" rpy="0 ${pi/2} 0"/> -->
        <origin xyz="${waist_length} 0 0" rpy="0 ${pi/2} 0"/>
        <parent link="waist_link"/>
        <child link="shoulder_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="0" upper="${pi}" velocity="100" effort="100"/> 
    </joint>

    <link name="shoulder_link">
        <visual>
            <origin xyz="${shoulder_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>                
                <cylinder length="${shoulder_length}" radius="${shoulder_radius}" />
            </geometry>
            <material name="cyan" />
        </visual>
        <collision>
            <origin xyz="${shoulder_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="${shoulder_length}" radius="${shoulder_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${shoulder_mass}" length="${shoulder_length}" radius="${shoulder_radius}">
            <origin xyz="${shoulder_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="arm_joint" type="revolute">
        <origin xyz="${shoulder_length} 0 0.15" rpy="0 0 0"/>
        <parent link="shoulder_link"/>
        <child link="arm_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="0" upper="${pi/2}" velocity="100" effort="100"/> 
    </joint>
    
    <link name="arm_link">
        <visual>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>                
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- camera_joint menggambarkan posisi relatif camera terhadap arm -->
    <joint name="camera_joint" type="fixed">
        <origin xyz="${arm_length} 0 ${arm_radius + 0.075}" rpy="0 0 0"/>
        <parent link="arm_link"/>
        <child link="camera_link"/>        
    </joint>

    <link name="camera_link">
        <visual>
            <origin xyz="-0.03 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.06 0.15 0.15" />
            </geometry>
            <material name="white" />
        </visual>
        <visual>
            <origin xyz="0.03 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="0.06" radius="0.04" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.12 0.15 0.15" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="0.12" y="0.15" z="0.15">
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <xacro:include filename="example_gazebo.xacro" />

</robot>

<!-- Referensi: -->
<!-- https://en.wikipedia.org/wiki/List_of_moments_of_inertia#List_of_3D_inertia_tensors -->
<!-- http://rutherford-robotics.com/PUMA/ -->
<!-- https://articulatedrobotics.xyz/ready-for-ros-7-urdf/ -->
<!-- https://articulatedrobotics.xyz/ready-for-ros-8-gazebo/ -->